-- ============================================================
-- بيانات كلية التربية - المستوى الرابع
-- ============================================================

-- 1. كلية التربية
INSERT INTO colleges (college_name, branch_id) VALUES
('كلية التربية', 1)
ON CONFLICT DO NOTHING;

-- 2. أقسام كلية التربية
INSERT INTO departments (department_name, college_id) VALUES
('قسم التعليم الأساسي', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم اللغة العربية وعلومها', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم اللغة الإنجليزية وتعليمها', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم الرياضيات وعلومها', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم العلوم الطبيعية', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم التربية الإسلامية', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم التاريخ والجغرافيا', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('قسم علم النفس والتربية الخاصة', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1))
ON CONFLICT DO NOTHING;

-- 3. مجموعات دراسية
INSERT INTO study_groups (group_name, group_type, college_id) VALUES
('A', 'نظري', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1)),
('B', 'نظري', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1))
ON CONFLICT DO NOTHING;

-- 4. مواد المستوى الرابع
INSERT INTO study_subjects (subject_name, subject_code, college_id, department_id, study_level_id, study_group_id, academic_semester_id, weekly_hours) VALUES
-- تعليم أساسي
('طرق تدريس الرياضيات', 'EDU401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('طرق تدريس اللغة العربية', 'EDU402', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('تصميم المناهج الدراسية', 'EDU403', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('التكنولوجيا في التعليم', 'EDU404', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 2),
-- لغة عربية
('النحو والصرف المتقدم', 'ARA401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم اللغة العربية وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('الأدب العربي الحديث', 'ARA402', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم اللغة العربية وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('البلاغة وال النقد الأدبي', 'ARA403', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم اللغة العربية وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
-- رياضيات
('التحليل الرياضي المتقدم', 'MTH401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم الرياضيات وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 4),
('الجبر الخطي', 'MTH402', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم الرياضيات وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('الاحتمالات والإحصاء', 'MTH403', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم الرياضيات وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
-- علوم
('الكيمياء المتقدمة', 'SCI401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم العلوم الطبيعية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('الفيزياء المتقدمة', 'SCI402', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم العلوم الطبيعية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('الأحياء الدقيقة', 'SCI403', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم العلوم الطبيعية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
-- تعليم إسلامي
('القرآن الكريم وعلومه', 'ISL401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التربية الإسلامية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('الفقه الإسلامي المقارن', 'ISL402', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التربية الإسلامية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
-- تاريخ وجغرافيا
('تاريخ الحضارة الإسلامية', 'HIS401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التاريخ والجغرافيا' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('الجغرافيا الطبيعية والبشرية', 'GEO401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التاريخ والجغرافيا' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
-- علم نفس
('علم النفس التربوي', 'PSY401', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم علم النفس والتربية الخاصة' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('التربية الخاصة والاشتباكات', 'PSY402', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم علم النفس والتربية الخاصة' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 3),
('إدارة الصف وتقنيات التدريس', 'PSY403', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم علم النفس والتربية الخاصة' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 2);

-- 5. جداول الدراسة
INSERT INTO study_schedules (college_id, academic_semester_id, day_of_week, start_time, end_time, study_subject_id, employee_id, external_employee_id, study_group_id, study_level_id, room, notes) VALUES
-- الأحد
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Sunday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'EDU401' LIMIT 1), 1, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C101', 'طرق تدريس الرياضيات'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Sunday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'ARA401' LIMIT 1), 2, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C102', 'النحو والصرف المتقدم'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Sunday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'MTH401' LIMIT 1), 3, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C201', 'التحليل الرياضي المتقدم'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Sunday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'SCI401' LIMIT 1), 4, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C202', 'الكيمياء المتقدمة'),
-- الاثنين
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Monday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'EDU402' LIMIT 1), 1, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C101', 'طرق تدريس اللغة العربية'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Monday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'ARA402' LIMIT 1), 2, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C102', 'الأدب العربي الحديث'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Monday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'MTH402' LIMIT 1), 3, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C201', 'الجبر الخطي'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Monday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'SCI402' LIMIT 1), 4, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C202', 'الفيزياء المتقدمة'),
-- الثلاثاء
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Tuesday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'EDU403' LIMIT 1), 1, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C101', 'تصميم المناهج الدراسية'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Tuesday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'ISL401' LIMIT 1), 5, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C103', 'القرآن الكريم وعلومه'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Tuesday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'MTH403' LIMIT 1), 3, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C201', 'الاحتمالات والإحصاء'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Tuesday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'HIS401' LIMIT 1), 6, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C203', 'تاريخ الحضارة الإسلامية'),
-- الأربعاء
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Wednesday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'EDU404' LIMIT 1), 1, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C104', 'التكنولوجيا في التعليم - معمل'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Wednesday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'ARA403' LIMIT 1), 2, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C102', 'البلاغة وال النقد الأدبي'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Wednesday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'SCI403' LIMIT 1), 4, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C204', 'الأحياء الدقيقة - معمل'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Wednesday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'GEO401' LIMIT 1), 6, NULL, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C203', 'الجغرافيا الطبيعية والبشرية'),
-- الخميس
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Thursday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'PSY401' LIMIT 1), 7, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C105', 'علم النفس التربوي'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Thursday', '10:00', '12:00', (SELECT id FROM study_subjects WHERE subject_code = 'ISL402' LIMIT 1), 5, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C103', 'الفقه الإسلامي المقارن'),
((SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), 1, 'Thursday', '08:00', '10:00', (SELECT id FROM study_subjects WHERE subject_code = 'PSY403' LIMIT 1), 7, NULL, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 4, 'C105', 'إدارة الصف وتقنيات التدريس');

-- 6. طلاب المستوى الرابع
INSERT INTO students (student_number, full_name, email, phone, college_id, department_id, study_level_id, study_group_id, academic_semester_id, status, total_earned_hours, total_gpa_points, cumulative_gpa, academic_status, enrollment_date, expected_graduation_date, nationality, birth_date, gender, address, password) VALUES
('2022011', 'عبدالرحمن محمد الصلاحي', 'abdulrahman.salehi@stu.ust.edu.ye', '771111111', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 255.0, 3.40, 'active', '2022-09-01', '2026-06-15', 'يمني', '2002-03-15', 'ذكر', 'صنعاء', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022012', 'نورهان عبدالملك الحوتي', 'norhan.houti@stu.ust.edu.ye', '772222222', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 240.0, 3.20, 'active', '2022-09-01', '2026-06-15', 'يمنية', '2002-07-20', 'أنثى', 'صنعاء', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022013', 'مصطفى أحمد العمري', 'mostafa.omari@stu.ust.edu.ye', '773333333', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التعليم الأساسي' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 232.5, 3.10, 'active', '2022-09-01', '2026-06-15', 'يمني', '2001-11-10', 'ذكر', 'تعز', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022021', 'سمير عبدالله القحطاني', 'samir.qahtani@stu.ust.edu.ye', '774444444', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم اللغة العربية وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 247.5, 3.30, 'active', '2022-09-01', '2026-06-15', 'يمني', '2002-01-05', 'ذكر', 'عدن', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022022', 'هند محمد البكري', 'hind.bakri@stu.ust.edu.ye', '775555555', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم اللغة العربية وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 262.5, 3.50, 'active', '2022-09-01', '2026-06-15', 'يمنية', '2002-05-15', 'أنثى', 'صنعاء', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022031', 'ياسر حسين المقطري', 'yasser.moqatri@stu.ust.edu.ye', '776666666', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم الرياضيات وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 270.0, 3.60, 'active', '2022-09-01', '2026-06-15', 'يمني', '2001-09-25', 'ذكر', 'إب', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022032', 'رقية أحمد النميري', 'ruqaya.numeiri@stu.ust.edu.ye', '777777777', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم الرياضيات وعلومها' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 255.0, 3.40, 'active', '2022-09-01', '2026-06-15', 'يمنية', '2002-02-14', 'أنثى', 'ذمار', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022041', 'جمال سالم العولقي', 'jamal.awlaqi@stu.ust.edu.ye', '778888888', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم العلوم الطبيعية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 247.5, 3.30, 'active', '2022-09-01', '2026-06-15', 'يمني', '2001-12-01', 'ذكر', 'حجة', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022042', 'مها عبدالقوي العرشي', 'maha.arshy@stu.ust.edu.ye', '779999999', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم العلوم الطبيعية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'B' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 240.0, 3.20, 'active', '2022-09-01', '2026-06-15', 'يمنية', '2002-04-20', 'أنثى', 'تعز', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022051', 'إبراهيم يوسف الغربلي', 'ibrahim.ghorbali@stu.ust.edu.ye', '770000000', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التربية الإسلامية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 262.5, 3.50, 'active', '2022-09-01', '2026-06-15', 'يمني', '2001-08-10', 'ذكر', 'صنعاء', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'),
('2022052', 'أماني خالد الزبيري', 'amani.zubairi@stu.ust.edu.ye', '771010101', (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1), (SELECT id FROM departments WHERE department_name = 'قسم التربية الإسلامية' LIMIT 1), 4, (SELECT id FROM study_groups WHERE group_name = 'A' AND college_id = (SELECT id FROM colleges WHERE college_name = 'كلية التربية' LIMIT 1) LIMIT 1), 1, 'active', 75, 247.5, 3.30, 'active', '2022-09-01', '2026-06-15', 'يمنية', '2002-06-15', 'أنثى', 'صنعاء', '$2a$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi');

-- 7. سجلات الدرجات
INSERT INTO academic_records (student_id, study_subject_id, grade_letter, grade_numeric, grade_points, is_pass, academic_semester_id) VALUES
-- عبدالرحمن الصلاحي - تعليم أساسي
((SELECT id FROM students WHERE student_number = '2022011' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU401' LIMIT 1), 'A-', 88, 3.7, true, 1),
((SELECT id FROM students WHERE student_number = '2022011' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU402' LIMIT 1), 'B+', 85, 3.3, true, 1),
((SELECT id FROM students WHERE student_number = '2022011' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU403' LIMIT 1), 'A', 92, 4.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022011' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU404' LIMIT 1), 'B', 80, 3.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022011' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'ISL401' LIMIT 1), 'A-', 87, 3.7, true, 1),
((SELECT id FROM students WHERE student_number = '2022011' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'PSY401' LIMIT 1), 'B+', 84, 3.3, true, 1),
-- نورهان الحوتي
((SELECT id FROM students WHERE student_number = '2022012' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU401' LIMIT 1), 'B', 80, 3.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022012' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU402' LIMIT 1), 'A-', 88, 3.7, true, 1),
((SELECT id FROM students WHERE student_number = '2022012' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU403' LIMIT 1), 'B+', 85, 3.3, true, 1),
((SELECT id FROM students WHERE student_number = '2022012' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU404' LIMIT 1), 'A', 91, 4.0, true, 1),
-- هند البكري - لغة عربية
((SELECT id FROM students WHERE student_number = '2022022' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'ARA401' LIMIT 1), 'A', 95, 4.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022022' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'ARA402' LIMIT 1), 'A-', 90, 3.7, true, 1),
((SELECT id FROM students WHERE student_number = '2022022' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'ARA403' LIMIT 1), 'A', 93, 4.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022022' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU401' LIMIT 1), 'B+', 86, 3.3, true, 1),
-- ياسر المقطري - رياضيات
((SELECT id FROM students WHERE student_number = '2022031' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'MTH401' LIMIT 1), 'A', 94, 4.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022031' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'MTH402' LIMIT 1), 'A-', 89, 3.7, true, 1),
((SELECT id FROM students WHERE student_number = '2022031' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'MTH403' LIMIT 1), 'A', 92, 4.0, true, 1),
((SELECT id FROM students WHERE student_number = '2022031' LIMIT 1), (SELECT id FROM study_subjects WHERE subject_code = 'EDU401' LIMIT 1), 'B+', 85, 3.3, true, 1);

-- 8. تقويم أكاديمي
INSERT INTO academic_calendar (event_title, description, event_date, event_type, academic_semester_id) VALUES
('بداية التسجيل', 'فترة تسجيل المواد الدراسية للفصل الأول', '2025-09-01', 'academic', 1),
('بداية المحاضرات', 'بداية الدوام الدراسي للفصل الأول', '2025-09-16', 'academic', 1),
('عطلة منتصف الفصل', 'عطلة قصيرة منتصف الفصل الأول', '2025-11-01', 'holiday', 1),
('اختبارات منتصف الفصل', 'اختبارات النصف الفصل الأول', '2025-11-15', 'exam', 1),
('نهاية المحاضرات', 'نهاية الدوام الدراسي للفصل الأول', '2026-01-10', 'academic', 1),
('اختبارات نهاية الفصل', 'الاختبارات النهائية للفصل الأول', '2026-01-12', 'exam', 1);
